/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;
import Model.ErrorLogData;
import java.util.Arrays;

/**
 *
 * @author Evan
 */
public class ErrorLog extends javax.swing.JFrame {

    /**
     * Creates new form ErrorLog
     */
    public ErrorLog(ArrayList<ErrorLogData> errors) {
        initComponents();
        
        StringBuilder sb = new StringBuilder();
        for (ErrorLogData error : errors)
        {
            if (error.getLine() >= 0)
            {
                sb.append("Line ");
                sb.append(error.getLine());
                sb.append(": ");
            }
            sb.append(error.getMessage());
            sb.append("\n");
        }
        errorTextArea.setText(sb.toString());
    }
    
    public ErrorLog(ErrorLogData error)
    {
        this(new ArrayList<>(Arrays.asList(error)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorScrollPane = new javax.swing.JScrollPane();
        errorTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error Log");

        errorTextArea.setEditable(false);
        errorTextArea.setColumns(20);
        errorTextArea.setForeground(new java.awt.Color(255, 0, 0));
        errorTextArea.setRows(5);
        errorTextArea.setWrapStyleWord(true);
        errorScrollPane.setViewportView(errorTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane errorScrollPane;
    private javax.swing.JTextArea errorTextArea;
    // End of variables declaration//GEN-END:variables
}
